version: '3'

services:
  www:
    image: 'tmvdl/stroll:www'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'
  io:
    image: 'tmvdl/stroll:io'
    build: './src/io'
    volumes:
      - './src/io:/app'
    ports:
      - '8080:80'
  github-release:
    image: 'github-release'
    build: './src'
    volumes:
      - './src:/app'
      - './dist:/dist'
